---

- hosts: "ios2"
  gather_facts: true
  connection: network_cli

  tasks:
   - import_tasks: /etc/ansible/playbook/bgp/R2BGP.yml

   - name: SAVE CONFIG
     ios_config:
       save: yes

   - ios_command:
      commands: show run | section router bgp
     register: router_bgp

   - name: disply router_bgp configuration
     debug: 
      msg: "{{ router_bgp }}"

- hosts: "ios1"
  gather_facts: true
  connection: network_cli

  tasks:
   - import_tasks: /etc/ansible/playbook/bgp/R1BGP.yml

   - name: SAVE CONFIG
     ios_config:
       save: yes

