--- 
- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: true
  hosts: all

  tasks:
    - name: Get config for IOS devices
      ios_command: 
       commands: show version

    - name: Display the config
      debug:
       msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
