---
- hosts: "IOS-Devices"
  gather_facts: true
  connection: local

  vars:
   cli:
     host: "{{ ansible_host }}"
     username: cisco
     password: cisco123

  tasks:
   - name: show version
     ios_command:
      commands:
           - show run
           - show version
      provider: "{{cli}}"
     register: config

   - name: save output to /etc/ansible/backup
     copy:
      content: "{{ config.stdout[0] }}"
      dest: "/etc/ansible/backup/show_run_{{ inventory_hostname }}.txt"


