---

- name: Generate router configuration files
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo

  roles:
    - MultiRouter

- name: router configuration
  hosts: ios
  
  tasks:
    - name: router configuration
      ios_config:
        src: /etc/ansible/roles/MultiRouter/tasks/configuration/RTR1.txt
        force: yes
