---
    
    - name: Create Template storage directory within the staging directory
      file: path=/etc/ansible/roles/switch/tasks/staging/{{ inventory_hostname }}/ state=directory
 
    - name: Generate Access Switch j2 template
      template: src=/etc/ansible/roles/switch/templates/{{ baselines.baseline }} dest=/etc/ansible/roles/switch/tasks/staging/{{ inventory_hostname }}/{{ inventory_hostname }}_Access.cfg
 
    - name: Generate ACL j2 template
      template: src=/etc/ansible/roles/switch/templates/{{ baselines.acl }} dest=/etc/ansible/roles/switch/tasks/staging/{{ inventory_hostname }}/{{ inventory_hostname }}_ACL.cfg
 
    - name: Append templates together to create final baseline configuration file
      assemble: src=/etc/ansible/roles/switch/tasks/staging/{{ inventory_hostname }}/ dest=/etc/ansible/roles/switch/tasks/complete/{{ inventory_hostname }}_FINAL.cfg
 
    - name: Delete Staging Directories
      file: path=/etc/ansible/roles/switch/tasks/staging/{{ inventory_hostname }}/ state=absent
